name: Golang-pip
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        container: golang:1.25
        steps:
            - uses: actions/checkout@v6.0.1

            - name: Download dependencies
              run: go mod download

            - name: Run unit tests
              run: |
                go test github.com/Elmar006/api-backend/handlers

            - name: Vet
              run: |
                go vet ./...
    
    deploy:
      name: Push Docker image to Docker Hub
      runs-on: ubuntu-latest
      needs: test
      if: startsWith(github.ref, 'refs/tags')
      steps:
        - name: Checkout
          uses: actions/checkout@v6.0.1

        - name: Set up Docker buildix
          uses: docker/setup-buildx-action@v3.12.0

        - name: Log in to Docker Hub
          uses: Docker/login-action@v3
          with:
            username: ${{secrets.ID_DOCKERHUB}}
            password: ${{secrets.TOKEN_DOCKERHUB}}
          
        - name: Extract metadata (tags, labels) for Docker
          id: meta 
          uses: docker/metadata-action@v5.10.0
          with:
            images: aristonm/parcel_package
            
        - name: Build and push Docker image
          uses: docker/build-push-action@v6.18.0
          with:
            context: . 
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}