name: Golang-pip
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        container: golang:1.25
        steps:
            - uses: actions/checkout@v6.0.1

            - name: Download dependencies
              run: go mod download

            - name: Run unit tests
              run: GOOS=linux GOARCH=amd64 go test

            - name: Vet
              run: |
                go vet ./...
    
   #deploy:
   